const urls = {
  picsum: "https://picsum.photos/v2/list",
};

const filters_kr = [
  "한옥",
  "해변 바로 앞",
  "한적한 시골",
  "열대 지역",
  "개인실",
  "최고의 전망",
  "기상 천외한 숙소",
  "국립공원",
  "인기 급상승",
  "멋진 수영장",
  "료칸",
  "캠핑장",
  "저택",
  "농장",
  "캐슬",
  "초소형 주택",
  "디자인",
  "신규",
  "상징적 도시",
  "통나무집",
  "와인 농장",
  "스키",
  "Luxe",
  "호수 근처",
  "속세를 벗어난 숙소",
  "키즈",
  "섬",
  "호숫가",
  "트리하우스",
  "사막",
  "B&B",
  "유서 깊은 주택",
  "북극",
  "유르트",
  "민수",
  "동굴",
  "보트",
  "창작 공간",
  "헛간",
  "복토 주택",
  "그랜드 피아노",
  "세상의 꼭대기",
  "서핑",
  "타워",
  "카사 파르티클라르",
  "A자형 주택",
  "스키를 탄 채로 출입 가능",
  "하우스보트",
  "돔하우스",
  "전문가급 주방",
  "리아드",
  "컨테이너하우스",
  "담무소",
  "골프장",
  "풍차",
  "마차",
  "무장애",
  "트룰로",
  "키클라데스 주택",
  "캠핑카",
  "해변 근처",
];

const footerNotice =
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";

const footerInfo = [
  "@ 2023 Test.inc",
  "개인정보 처리방침",
  "이용약관",
  "사이트맵",
  "한국의 변경된 환불 정책",
  "회사 세부 정보",
];

const footerKR = ["한국어 (KR)", "\\ KRW", "지원 및 참고 자료"];

export { urls, filters_kr, footerNotice, footerInfo, footerKR };
